language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/Color_Cycle
  - PLATFORMIO_PROJECT_DIR=examples/Project_Template
  - PLATFORMIO_PROJECT_DIR=examples/Red_Blink

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

